variables:
  GIT_DEPTH: 10
  S3_BUCKET_NAME: "atium.playground.repo"
  AWS_DEFAULT_REGION: "eu-west-1"
  ZIPPED_REPO: "bundle.zip"

copy-code-to-s3:
  image: amazonlinux
  only:
    - master
  script:
    - |
      echo "Installing required packages"
      yum install -y zip
      curl https://bootstrap.pypa.io/get-pip.py | python
      pip install awscli --upgrade

      echo "Zipping and copying code to $S3_BUCKET_NAME/$ZIPPED_REPO"
      zip -q -r $ZIPPED_REPO *
      aws s3 cp $ZIPPED_REPO s3://$S3_BUCKET_NAME
